apiVersion: spec.keptn.sh/0.2.3
kind: "Shipyard"
metadata:
  name: "stages"
spec:
  stages:
    - name: "dev"
      sequences:
      - name: "delivery"
        tasks:
        - name: "deployment"
          properties:
            deploymentstrategy: "blue_green_service"
        - name: "test"
          properties:
            teststrategy: "functional"
        - name: "evaluation"
        - name: "release"
      - name: "rollback"
        triggeredOn:
          - event: "dev.delivery.finished"
            selector:
              match:
                result: fail
        tasks:
        - name: "rollback"