---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stages
  labels:
    app: stages
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: stages
  template:
    metadata:
      labels:
        app: stages
    spec:
      containers:
      - image: "{{ .Values.image }}"
        imagePullPolicy: Always
        name: stages
        env:
          - name: DT_CUSTOM_PROP
            value: "keptn_project={{ .Values.keptn.project }} keptn_service={{ .Values.keptn.service }} keptn_stage={{ .Values.keptn.stage }} keptn_deployment={{ .Values.keptn.deployment }}"
          - name: KEPTN_PROJECT
            value: "{{ .Values.keptn.project }}"
          - name: KEPTN_STAGE
            value: "{{ .Values.keptn.stage }}"
          - name: KEPTN_SERVICE
            value: "{{ .Values.keptn.service }}"
          - name: KEPTN_DEPLOYMENT
            value: "{{ .Values.keptn.deployment }}"
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi