apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: stagessvc-canary
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: stages
  type: LoadBalancer
status:
  loadBalancer: {}
